import { useCallback, useEffect, useState } from "react";

type Point = { timestamp: number; value: number };
type Event = { event: string; time: number; error_percentage?: number; request_rate?: number };
type Workload = { name: string; desired_replicas: number; ready_replicas: number; available: boolean };
type Overview = { generated_at: string; system: {state: "healthy" | "degraded"; message: string}; traffic: {state: string; stable?: number; canary?: number; generation?: number; accepted?: boolean; message?: string}; workloads: {state: string; stable?: Workload; canary?: Workload; controller?: Workload}; health: {state: string; threshold_percent?: number; window_seconds?: number; versions?: Record<string, {error_percent: number | null; request_rate: number | null}>; error_history?: Record<string, Point[]>; request_history?: Record<string, Point[]>}; controller: {ready?: boolean; latest_event?: Event}; events: {items?: Event[]} };

const percent = (value?: number | null) => value == null ? "No recent data" : `${value.toFixed(2)}%`;
const rate = (value?: number | null) => value == null ? "No recent data" : `${value.toFixed(2)} req/s`;
const clock = (value?: number) => value ? new Date(value * 1000).toLocaleTimeString() : "Waiting for activity";

function Chart({title, data, threshold}: {title: string; data?: Record<string, Point[]>; threshold?: number}) {
  const all = ["v1", "v2"].flatMap(v => data?.[v] ?? []), max = Math.max(1, threshold ?? 0, ...all.map(p => p.value));
  const start = all[0]?.timestamp ?? Date.now() / 1000 - 1800, end = all.at(-1)?.timestamp ?? Date.now() / 1000;
  const line = (series: Point[]) => series.map((p, i) => `${i ? "L" : "M"}${(100 * (p.timestamp-start)/Math.max(end-start, 1)).toFixed(1)},${(92 - 78 * p.value/max).toFixed(1)}`).join(" ");
  return <section className="panel chart"><div className="heading"><div><label>Last 30 minutes</label><h2>{title}</h2></div><span className="legend"><i className="stable"/>Stable <i className="canary"/>Canary</span></div>{all.length ? <svg viewBox="0 0 100 100" preserveAspectRatio="none">{[25,50,75].map(y=><line key={y} x1="0" x2="100" y1={y} y2={y}/>) }{threshold != null && <line className="threshold" x1="0" x2="100" y1={92-78*threshold/max} y2={92-78*threshold/max}/>}<path className="stable-line" d={line(data?.v1 ?? [])}/><path className="canary-line" d={line(data?.v2 ?? [])}/></svg> : <p className="empty">Waiting for Prometheus history</p>}</section>;
}

function WorkloadRow({item}: {item?: Workload}) { return item ? <div className="workload"><div><strong>{item.name}</strong><span>{item.ready_replicas}/{item.desired_replicas} replicas ready</span></div><i className={item.available ? "dot good" : "dot warn"}/></div> : null; }

function Dashboard({data}: {data: Overview}) { const health = data.health; return <main>
  <section className="hero panel"><div><label>Local Kubernetes MVP</label><h1>Release control, at a glance.</h1><p>Watch the canary, confirm the route, and see whether automatic recovery has the evidence it needs.</p></div><div className={data.system.state === "healthy" ? "system healthy" : "system degraded"}><i className="dot"/><div><strong>{data.system.state === "healthy" ? "System connected" : "System needs attention"}</strong><p>{data.system.message}</p></div></div></section>
  <section className="metrics"><article className="panel"><label>Live traffic split</label>{data.traffic.state === "available" ? <><div className="split"><b>{data.traffic.stable}%</b><span>stable</span><b>{data.traffic.canary}%</b><span>canary</span></div><div className="bar"><i style={{width:`${data.traffic.stable}%`}}/><em style={{width:`${data.traffic.canary}%`}}/></div><p>{data.traffic.accepted ? `Route generation ${data.traffic.generation} accepted by Gateway` : "Gateway has not accepted this route"}</p></> : <p className="empty">{data.traffic.message}</p>}</article>
  <article className="panel"><label>Canary error rate</label><b className={(health.versions?.v2.error_percent ?? 0) > 5 ? "danger number" : "number"}>{percent(health.versions?.v2.error_percent)}</b><p>Rollback above {health.threshold_percent ?? 5}% over {health.window_seconds ?? 60}s</p></article>
  <article className="panel"><label>Canary request rate</label><b className="number">{rate(health.versions?.v2.request_rate)}</b><p>Sufficient traffic is required for a recovery decision.</p></article>
  <article className="panel"><label>Recovery controller</label><b className="number">{data.controller.ready ? "Ready" : "Unavailable"}</b><p>{data.controller.latest_event ? `${data.controller.latest_event.event.replaceAll("_", " ")} · ${clock(data.controller.latest_event.time)}` : "Waiting for controller activity"}</p></article></section>
  <section className="content"><div><Chart title="Canary error percentage" data={health.error_history} threshold={health.threshold_percent}/><Chart title="Request rate" data={health.request_history}/></div><aside className="panel workloads"><label>Workloads</label><h2>Release readiness</h2><WorkloadRow item={data.workloads.stable}/><WorkloadRow item={data.workloads.canary}/><WorkloadRow item={data.workloads.controller}/><p>Traffic controls will appear after tracked operations and safeguards are added.</p></aside></section>
  <section className="panel events"><label>Recovery controller</label><h2>Recent activity</h2>{data.events.items?.length ? <ol>{data.events.items.map((event, index)=><li key={`${event.time}-${index}`}><i className={event.event.includes("error") || event.event === "unhealthy" ? "dot warn" : "dot good"}/><div><strong>{event.event.replaceAll("_", " ")}</strong><p>{event.error_percentage != null ? `${percent(event.error_percentage)} canary errors` : event.request_rate != null ? rate(event.request_rate) : "Controller status update"}</p></div><time>{clock(event.time)}</time></li>)}</ol> : <p className="empty">No controller events have been recorded yet.</p>}</section>
</main>; }

export function App() { const [data, setData] = useState<Overview>(); const [error, setError] = useState<string>(); const [updated, setUpdated] = useState<Date>(); const load = useCallback(async () => { try { const response = await fetch("/api/overview", {cache:"no-store"}); const payload = await response.json(); if (!response.ok) throw new Error(payload.system?.message ?? "Dashboard unavailable"); setData(payload); setUpdated(new Date()); setError(undefined); } catch (reason) { setError(reason instanceof Error ? reason.message : "Dashboard unavailable"); } }, []); useEffect(() => { void load(); const timer = setInterval(() => void load(), 10000); return () => clearInterval(timer); }, [load]); return <><header><a className="brand">CANARY <span>CONTROL</span></a><nav><a className="active">Dashboard</a><a>Verification <small>Coming next</small></a></nav><div className="refresh"><i className="dot good"/>{updated ? `Updated ${updated.toLocaleTimeString()}` : "Connecting"}<button onClick={()=>void load()}>Refresh</button></div></header>{error && <div className="alert">Unable to refresh the dashboard: {error}</div>}{data ? <Dashboard data={data}/> : <main className="loading"><i/><p>Connecting to the local MVP…</p><small>Start the management API, Kubernetes cluster, and Prometheus to see live status.</small></main>}</>; }
